"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { loadRealMeta } from "@/lib/data";
import type { RealMeta } from "@/lib/types";

/**
 * Data-status strip under the header. Reads the real-data metadata (absent until the first ingestion run) and
 * shows one chip per layer: what is real, what is a model output and how it stands, what is still sample.
 * The full explanation sits behind a "details" toggle so the strip stays one line.
 */
export function SampleBanner() {
  const [real, setReal] = useState<RealMeta | null | undefined>(undefined);
  useEffect(() => {
    loadRealMeta().then(setReal);
  }, []);
  if (real === undefined) return <div role="status" className="h-8 border-b border-rule bg-surface-2" aria-label="Checking data status" />;
  if (!real) {
    return (
      <div role="status" className="border-b border-sample/40 bg-sample/10 px-4 py-1.5 text-center text-xs font-semibold text-sample">
        SAMPLE DATA · every value on this site is generated by a seeded script for interface development. Nothing shown is a real measurement.
      </div>
    );
  }
  const cov = Object.values(real.coverage);
  const withFacts = cov.filter((c) => c.actions).length;
  const withParliament = cov.filter((c) => c.parliament_available).length;
  const withMedia = cov.filter((c) => c.media_available).length;
  const tm = real.text_model;
  const classified = cov.reduce((n, c) => n + (c.parliament_classified ?? 0) + (c.media_classified ?? 0), 0);
  const textLabel = classified > 0 && tm?.method ? (tm.validated && tm.kappa_stance_pooled !== null ? `validated κ=${tm.kappa_stance_pooled.toFixed(2)}` : "zero-shot baseline") : "not classified";
  const chips: { label: string; value: string; tone: "facts" | "model" | "interp" | "sample" }[] = [
    { label: "Facts", value: `real · ${withFacts}/12`, tone: "facts" },
    { label: "Text", value: `records ${withParliament}/${withMedia} · stance ${textLabel}`, tone: classified > 0 ? "model" : "facts" },
    { label: "Indices", value: real.layers?.analysis === "real" ? `computed ${real.quant_model?.method_version ?? ""}` : "sample", tone: real.layers?.analysis === "real" ? "model" : "sample" },
    { label: "Forecasts", value: real.layers?.forecast === "real" ? "backtested" : "sample", tone: real.layers?.forecast === "real" ? "model" : "sample" },
    { label: "Analysis", value: real.layers?.interpretation ? (real.layers.interpretation === "generated+human" ? "generated + owner" : "generated") : "pending", tone: real.layers?.interpretation ? "interp" : "sample" },
  ];
  const toneCls = { facts: "border-facts/40 text-facts", model: "border-model/40 text-model", interp: "border-interp/40 text-interp", sample: "border-sample/50 text-sample" };
  return (
    <div role="status" className="border-b border-rule bg-surface-2">
      <details className="mx-auto max-w-7xl px-4">
        <summary className="flex list-none flex-wrap items-center gap-x-3 gap-y-1 py-1.5 text-[11px] text-ink-2 [&::-webkit-details-marker]:hidden">
          <span className="eyebrow">Data status</span>
          <span className="text-ink-3">ingested {real.generated_on} · {real.sources_ok.length} sources</span>
          <span className="hidden flex-wrap gap-1 sm:flex">
            {chips.map((c) => (
              <span key={c.label} className={`chip border bg-card normal-case tracking-normal ${toneCls[c.tone]}`} title={`${c.label}: ${c.value}`}>
                <span className="font-semibold">{c.label}</span>
                <span className="font-normal text-ink-2">{c.value}</span>
              </span>
            ))}
          </span>
          <span className="text-ink-3 underline decoration-dotted">what is real?</span>
        </summary>
        <p className="flex flex-wrap gap-1 pb-1 sm:hidden">
          {chips.map((c) => (
            <span key={c.label} className={`chip border bg-card normal-case tracking-normal ${toneCls[c.tone]}`}><span className="font-semibold">{c.label}</span><span className="font-normal text-ink-2">{c.value}</span></span>
          ))}
        </p>
        <p className="pb-2 text-[11px] leading-relaxed text-ink-2">
          Facts (actions, trade, governance) are real data from {real.sources_ok.length} sources, ingested {real.generated_on}, covering {withFacts} of 12 countries; every block is labelled per panel. Parliament and media carry real records for {withParliament} and {withMedia} countries; stance, tone, translations and narratives are model outputs ({textLabel}). The influence index, concentration measures, say–do gap, flags, event studies, regressions and the finance network are computed from the sourced data (method {real.quant_model?.method_version ?? "–"}); forecasts come from backtested models (naive persistence where nothing beat it) and scenarios are labelled as such; the written analysis is generated from named indicators{real.layers?.interpretation === "generated+human" ? ", with the project owner's own text shown apart" : "; no human-written text exists yet"}. Details on the <Link href="/methodology" className="underline">methodology page</Link>.
        </p>
      </details>
    </div>
  );
}
