import { ForecastMetrics } from "@/components/methodology/ForecastMetrics";
import { QuantMethods } from "@/components/methodology/QuantMethods";
import { ValidationMetrics } from "@/components/methodology/ValidationMetrics";
import Link from "next/link";
import { LayerLabel } from "@/components/ui/Badges";

export const metadata = { title: "Methodology · US–China Critical Minerals Tracker" };

export default function MethodologyPage() {
  return (
    <div className="prose-doc mx-auto max-w-3xl px-4 py-6">
      <h1 className="text-2xl font-semibold">Methodology</h1>
      <p>
        This page documents every index, model, data source and known limitation, with validation scores as they become available. It is regenerated with each data release. Sections marked pending describe planned methods; everything else is live and labelled per block on the site.
      </p>

      <nav aria-label="Contents" className="toc card mt-4 p-3">
        <p className="eyebrow mb-1">Contents</p>
        <ol className="grid gap-x-6 gap-y-0.5 sm:grid-cols-2">
          {Object.entries({ layers: "Three layers, kept apart", reliability: "Source reliability ratings", missing: "Missing and estimated data", text: "Text analysis (Phase 3)", statements: "Political statements", index: "Influence index (Phase 4)", concentration: "Concentration and dependence", flows: "Money and trade flows", events: "Event studies and panels", flags: "Say–do gap and flags", networks: "Networks", forecasting: "Forecasting (Phase 5)", insights: "Insights and scenarios", writing: "Written analysis (Phase 6)", refresh: "Refresh schedule", limitations: "Known limitations" }).map(([id, label], i) => (
            <li key={id}><a href={`#${id}`}><span className="tabular-nums text-ink-3">{i + 1}.</span> {label}</a></li>
          ))}
        </ol>
      </nav>

      <h2 id="layers">Three layers, kept apart</h2>
      <p>Everything on the site belongs to one of three layers and is labelled as such:</p>
      <ul>
        <li><LayerLabel layer="facts" /> Sourced data: trade flows, loans, deals, concessions, production, parliamentary records, article metadata. Each row carries its source, retrieval date, original language, reliability rating and confidence level.</li>
        <li><LayerLabel layer="model" /> Model outputs: the influence index, concentration measures, stance and tone scores, narratives, say–do gap, anomaly flags, network metrics, forecasts. Each carries the method or model version and, where it exists, its validation status.</li>
        <li><LayerLabel layer="interpretation" /> Written analysis generated from named indicators by fixed templates (each sentence lists the indicators behind it), plus the project owner&apos;s own writing, shown apart and marked as such.</li>
      </ul>

      <h2 id="reliability">Source reliability ratings</h2>
      <table>
        <thead><tr><th>Rating</th><th>Meaning</th></tr></thead>
        <tbody>
          <tr><td>Official</td><td>Governments, central banks, statistical offices, legislatures, multilateral organisations, exchanges and regulators.</td></tr>
          <tr><td>Independent / academic</td><td>Universities, research centres, NGOs, independent press.</td></tr>
          <tr><td>Partisan</td><td>Outlets or organisations with a documented political alignment or advocacy mission. Used, but labelled.</td></tr>
          <tr><td>State-controlled media</td><td>State-owned outlets and government communication (Xinhua, People&apos;s Daily, Chinese embassies, Guyana Chronicle, Venezuelan ministries).</td></tr>
          <tr><td>Analysis</td><td>Think-tank commentary. Context only, never ingested as data.</td></tr>
        </tbody>
      </table>
      <p>The full registry with URL, coverage years, update frequency, license and verification status is on the <Link href="/sources" className="underline">Sources page</Link>.</p>

      <h2 id="missing">Missing and estimated data</h2>
      <p>Missing data is shown as missing (&ldquo;no data&rdquo; on the map, empty lists in the panel). Nothing is estimated silently. Where a value is derived (for example an implicit lithium price computed as export value divided by quantity), the method is stated next to it. Partner-reported (mirror) trade data is labelled as such; discrepancies between national, partner, Chinese and US customs figures are reported, not reconciled.</p>

      <h2 id="statements">Political statements (the owner&apos;s dataset)</h2>
      <p>The Politics tab and the region page show a hand-supplied dataset of 395 statements and acts about minerals in Latin America (March 2019 to October 2026): presidents, ministers, governors, legislators and legislative bodies, courts, state companies, US and Chinese officials, and others. It was collected by AI research agents with web search under a fixed codebook; every record carries the source URL actually consulted and a verification level (primary source seen, reported by media, unverified), from which the site derives the record&apos;s reliability rating (official, independent media, state media, analysis, partisan) and its confidence. Quotes are exact excerpts of at most 30 words, shown in the original language with an English rendering. The dataset&apos;s stance coding toward China and the United States (positive, neutral, mixed, negative, not mentioned) is interpretive and has <strong>not been validated</strong> by a second coder: the site labels it &ldquo;coded under the dataset&apos;s codebook&rdquo;, summarises it by year for a country&apos;s own actors as a mean of +1 / 0 / −1 with the number of statements behind it, and never feeds it into the influence index or the say–do gap. Mexico and Panama records lie outside the twelve countries and are not shown; region-wide records appear on the region page. Coverage is uneven and thin before 2022 (see Limitations).</p>

      <h2 id="index">Influence index (Phase 4)</h2>
      <p>A composite indicator per country, year and actor (and per mineral where the country trades it), built along the OECD/JRC Handbook on Constructing Composite Indicators. Six components measure observable ties to the actor: the share of the country&apos;s mineral exports going to it and of its mineral imports coming from it (UN Comtrade, reporter&apos;s own data), documented official-finance commitments from its institutions over the last three years relative to GDP (AidData for China, DFC for the United States; central-bank swap-line drawdowns excluded), public external debt owed to it relative to GDP (World Bank IDS, China only: no equivalent source exists for the United States), UN General Assembly voting agreement, and the mean legislative stance toward it from the text model (years with at least five scored records). <strong>No imputation:</strong> a missing input leaves the component unavailable with the reason recorded, the index is the equal-weighted mean of the components that exist, and it is not computed from fewer than three. Values are normalised by winsorised min–max over the whole panel with both actors on one scale, so a US value and a Chinese value are comparable; because US trade shares and finance are small next to China&apos;s, US values are low by construction, which is the finding, not an artefact. <strong>Uncertainty:</strong> weights are redrawn hundreds of times from a Dirichlet around equal weights and the normalisation switched to percentile ranks in half of the draws; the band on every value is the 5th–95th percentile of the results, and the rank stability of the country ranking is reported below. The index is a description of recorded ties, not a measure of intent.</p>
      <QuantMethods />

      <p><strong>Your own weights.</strong> The Drivers block of the Analysis tab lets a reader re-weight the six components for the selected year and see the resulting composite next to the published value. It is a what-if computed in the browser from the same normalised components (a weight of zero drops a component; at least three must remain); it is never stored, never replaces the published index and never feeds the ranking or the forecasts.</p>

      <h2 id="concentration">Concentration and dependence (Phase 4)</h2>
      <p>For every country, mineral and year with reported trade: the shares of exports going to the United States, to China and to the rest of the world, the same for imports, the two-power share, and a revealed comparative advantage index against the pooled twelve-country export basket (world totals are not in the warehouse). A Herfindahl–Hirschman index over all export destinations is <strong>not computed</strong>: the free Comtrade access used so far returns partner totals for the United States, China and the world only; it is stored as null with that reason, never estimated. A partner row absent from a reporter&apos;s Comtrade answer for a year it did report is read as no recorded flow and noted as such.</p>

      <h2 id="flows">Money and trade flows on the map</h2>
      <p>The map&apos;s flow views draw one arc per country and actor from <code>flows.json</code>, a file the pipeline exports for all twelve countries. <strong>Money</strong> is the sum of documented finance commitments by country, origin and year from the de-duplicated finance events (the same records as the Actions tab); swap-line drawdowns and amounts from lower-confidence records are kept apart and never added, and a year with events but no published amount keeps an amount of zero with the count shown, so an absence is stated rather than drawn as nothing. <strong>Trade</strong> is reported exports to each actor (UN Comtrade, reporter&apos;s own data) for all minerals or one core mineral. The window is the selected year, the three years to it, or every year since 2008. Arc width follows the square root of the amount on a scale shared by every arc in the view; the faint end is the origin; the arcs run between country centroids and Washington or Beijing as schematic anchors, not along real routes. Hovering an arc, or opening the table in the panel, gives the amount, the counts and the sources behind it; a window beyond a source&apos;s last year (AidData ends in 2021) is flagged.</p>

      <h2 id="text">Text analysis (Phase 3)</h2>
      <p>Multilingual pipeline (Spanish, Portuguese, English, Dutch). The unit of analysis is the title of a legislative record plus its summary where the legislature publishes one, or a headline; no article text is stored. Documents are coded for stance toward the United States and toward China on a five-point scale (−2 to +2), scored only when the actor is named (otherwise the stance is “not applicable”, never zero), plus tone (−1 to +1) and topic, following the written codebook in <code>pipeline/config/codebook.md</code>.</p>
      <p>Classification uses open-weight models on CPU only. <strong>Baseline:</strong> a multilingual natural-language-inference model (mDeBERTa-v3-base-xnli) scores three hypotheses per actor (favourable, critical, neutral mention); the winning hypothesis gives the sign and its probability the strength (≥0.75 → ±2, else ±1; below 0.5 the model has no clear reading and the stance is 0). Tone is the positive-minus-negative score of a multilingual sentiment model. <strong>Trained model:</strong> multilingual sentence embeddings (paraphrase-multilingual-MiniLM) with a logistic-regression head trained on the adjudicated sample inside the same workflow; it replaces the baseline on the site only if it beats it on the held-out split. Machine translations of titles (opus-mt) are labelled as such and the original is always shown. Narratives are clusters of headline embeddings (k-means) labelled by class-based TF-IDF keywords, with example documents. Media attention is the share of each year&apos;s coverage naming an actor.</p>
      <p><strong>Validation.</strong> A stratified random sample of 300 documents (country × document type × whether an actor is named) is coded by two coders: the project owner and an LLM coder inside development sessions, blind to each other and to the model, then adjudicated. Inter-coder agreement (Cohen&apos;s kappa, Krippendorff&apos;s alpha) and per-class precision, recall and F1 of the baseline and the trained model against the adjudicated labels are published below as soon as they exist. Until then every stance and tone value on the site is tagged “zero-shot baseline, not yet validated”.</p>
      <ValidationMetrics />

      <h2 id="events">Event studies and panels (Phase 4b)</h2>
      <p><strong>Event studies.</strong> The dated events in <code>pipeline/config/events.yaml</code> (US critical-minerals orders and the IRA, Chinese export controls of 2023–2025, Chile&apos;s lithium strategy, Argentina&apos;s RIGI, Bolivia&apos;s 2019 crisis, Peru&apos;s Chancay port, the 2025 Section 232 copper tariff, among others; each dated, typed and sourced, and marked draft until the project owner has reviewed it) are tested two ways on annual export shares. The event window compares, for each country and actor, the mean share in the two years after the event with the two years before (the event year left out); the placebo p-value is the share of the same statistic computed at every other year of that country&apos;s series that is at least as large. For events touching some countries only, a difference-in-differences subtracts the mean change of the other countries, with a permutation placebo over country subsets of the same size (at least three controls). With twelve countries, annual data and policies that respond to the same world, these are associations; no causal language is used. Events of 2025 and later have no post-event years yet and are listed as pending.</p>
      <p><strong>Panel regressions.</strong> Four outcomes (a country&apos;s export share to China, to the United States, and the two import shares) on five standardised regressors: the actor&apos;s documented official-finance commitments over the previous three years relative to GDP, lagged one year; UN General Assembly voting agreement with the actor; electoral democracy (V-Dem); rule of law (WGI); mineral rents in GDP. Country effects absorb endowment and geography, year effects absorb world prices and demand; a country-effects-only variant is the robustness check. With eleven clusters the inference is fragile, so every coefficient is shown with its cluster-robust standard error, a wild cluster bootstrap p-value and the range it takes when each country is dropped in turn. The table below is regenerated with each data release.</p>

      <h2 id="flags">Say–do gap and flags (Phase 4)</h2>
      <p><strong>Say–do gap:</strong> the legislature&apos;s mean stance toward an actor in a year (at least five scored records; a text-model output carried with the classifier&apos;s validation status) standardised within the actor, minus the standardised year-on-year change of the economic-ties sub-index (trade shares, finance, debt). Positive: words warmer than the flows; negative: flows outrun the words. Media stance joins once the headline record is long enough. <strong>Flags</strong> are rules on the sourced series, each with an evidence level: a share of exports to an actor moving 20 points or more in a year, or documented commitments of 1% of GDP or more in a year (<em>documented</em>: the movement is in official data); commitments of 0.5% of GDP or more not followed by any change in the mineral trade share within two years, or the debt stock owed to China rising 20% and US$100 million in a year with no commitment recorded (<em>strongly indicated</em>: two sourced series disagree); a say–do gap beyond two standard deviations (<em>speculative</em>: a model output is involved). Swap-line drawdowns are flagged as rescue lending and kept out of the finance component. Mirror-data discrepancies and third-country subsidiaries wait for partner-reported trade and ownership data. A flag is never presented as an established fact.</p>

      <h2 id="networks">Networks (Phase 4)</h2>
      <p>The finance records give a lender–recipient graph: funding institutions (policy banks, central banks, ministries, agencies, companies) linked to the receiving agencies named in each record, weighted by the amounts committed. Degree, weighted degree, betweenness, eigenvector centrality (on the largest connected component) and greedy-modularity communities are computed on the twelve-country graph and shown per country. Events that name no recipient are left out and counted. Ownership chains through third-country subsidiaries are not in the graph yet: the contracts database carries no company names and cadastres exist for one country.</p>

      <h2 id="forecasting">Forecasting (Phase 5)</h2>
      <p>Two targets per country and actor are forecast to 2030: the influence index and the share of mineral exports going to the actor. The series are annual and at most eighteen points long, so only simple models are fitted and they are made to compete: naive persistence (last value, with uncertainty from bootstrapped yearly changes), a random walk with drift, the same drift partially pooled across countries by empirical-Bayes shrinkage (the hierarchical element), an AR(1) on yearly changes, and a damped local linear trend fitted by maximum likelihood with a Kalman filter (the state-space element). Each model produces simulated paths; on expanding-window backtests from 2015 onward every model is scored at horizons of one to three years by the continuous ranked probability score (CRPS), the absolute error of the median and the coverage of its 80% and 95% bands, pooled over the countries. The model published for a target is the one with the lowest pooled CRPS if it beats naive persistence; otherwise persistence itself is published and labelled. Bands are the 5th–95th and 25th–75th percentiles of the simulated paths. Scenarios are Monte Carlo paths of the published model with an explicit, stated yearly shift (for example &ldquo;the share to China grows 2 points a year faster&rdquo;); they are what-ifs, not forecasts. A five-year horizon on seventeen annual observations is a long reach: the bands are wide, coverage in the backtests is below nominal for the share forecasts, and the methodology table below is regenerated with every data release.</p>
      <ForecastMetrics />

      <h2 id="insights">Insights and scenarios</h2>
      <p>The Insights page sets the layers against each other. The pipeline&apos;s export step computes one file, <code>insights.json</code>, from the tables the other pages already use (DECISIONS 59): for each country the latest reported trade year with every mineral, the share series, documented commitments by year, the latest index components with the published composite, the forecast paths of the three scenarios, and the &ldquo;words&rdquo; (the executives&apos;, US officials&apos; and Chinese officials&apos; coded statements by year, the legislature&apos;s zero-shot stance, press tone). From these it builds <strong>contrast indicators</strong>, each only where its inputs exist and each with the ids of the rows it rests on: executives&apos; coded stance toward a power pooled over the latest three statement years (at least three positions) against the share of exports going there; the minerals named in statements against the minerals that earn the export value (mismatch = half the sum of the absolute gaps); a hedging balance (1 = equally warm to both powers, 0 = one-sided, from at least four positive positions); the legislature&apos;s stance (halved, from −2..+2) against the executives&apos; in the same year; press tone against the executives&apos; stance; the parity gap (half the difference between what China and the United States buy, at constant totals); the 2030 share under each published scenario; the exposure of the largest priced mineral; and US officials&apos; statements about a country against DFC money. Region-wide: statements by bloc against commitments by origin (both finance sources cover every sector, the part the adapters tagged to a mineral is shown apart; the money ratio runs on 2015–2021 because AidData ends in 2021), event echoes (post-minus-pre changes of the export share grouped by the event&apos;s actor and type), the two-way fixed-effects regressions with the regressors&apos; standard deviations, annual prices per mineral and US policy attention (documents per year). Scales differ and are never added: statements −1..+1 (the dataset&apos;s codebook, not validated), legislative stance −2..+2 (zero-shot, not validated), media tone −1..+1, the index 0–100.</p>
      <p><strong>Findings</strong> are template sentences that fire only when their inputs exist, each with its indicator ids, a <strong>evidence level</strong> and a &ldquo;why it could be wrong&rdquo; caveat: <em>strong</em> = facts layers with dozens of records or full series; <em>moderate</em> = facts plus one unvalidated coding with ten or more records, or panel associations; <em>thin</em> = fewer than ten records, a single year, press tone, zero-shot stance or draft events. A bold headline with a thin meter is a hypothesis, not a result.</p>
      <p><strong>The scenario studio</strong> is arithmetic on published numbers, done in the browser and never stored (DECISIONS 60). The <em>pull</em> slider blends the three published scenario paths linearly (the pipeline&apos;s scenarios are the baseline Monte Carlo paths plus a linear yearly shift, so an intermediate pull is exact except where a published path was clipped at 0 or 1); the <em>shock</em> adds the mean post-minus-pre change observed after an event family, with its middle half, to the blended share path from the chosen year (a historical echo, never a prediction; events still in draft are labelled so on the page); the <em>redirect</em> moves a share of a mineral&apos;s exports to China toward the United States or the rest of the world and recomputes the shares at constant totals; the <em>finance</em> lever sets each actor&apos;s yearly commitments at a multiple of its average (China over 2015–2021, the DFC over 2022–2024) and turns it into the index&apos;s finance component (three years over GDP); the <em>price</em> lever revalues the largest priced mineral&apos;s exports at constant volumes. The index what-if applies the published formula (equal weights over the available normalised components, at least three, winsorised min–max with the bounds the pipeline exports) to the reader&apos;s numbers; it may use components the published year lacks, and says how many it used next to the published value. The levers serialise into the URL so a scenario can be shared. Every block carries its layer label; the reading at the end is AI-drafted from the indicators and labelled so until the project owner reviews it (DECISIONS 61).</p>

      <h2 id="writing">Written analysis (Phase 6)</h2>
      <p>The interpretation layer has two parts, kept apart on every page. <strong>Generated briefs:</strong> for each country (where it stands, trade, finance and debt, politics, dated events, outlook, what the data cannot say) and for the region (ranking, movers, trade pattern, finance pattern, statistical evidence, outlook, caveats), fixed templates turn the computed indicators into sentences. A template fires only when every indicator it cites exists; otherwise the brief says what is missing. Every sentence carries the ids of the indicators it rests on (<code>table:field:actor:year</code>, for example <code>index_value:influence:CN:2024</code> or <code>anomaly_flag:BRA-sudden_trade_shift-2009-CN</code>), shown on click, and model outputs are named as such in the sentence. Trend words follow fixed thresholds: an index change under 2 points over five years, or a share change under 3 points, is &ldquo;broadly flat&rdquo;. The briefs are regenerated with every data release; a section whose text differs from the previous release is marked &ldquo;updated&rdquo;. No language model writes any of this text. <strong>Human-written interpretation:</strong> the project owner&apos;s own Markdown files under <code>data/manual/interpretation/</code>, with author, date and a reviewed flag, shown in their own box labelled as the owner&apos;s writing; the pipeline never writes or edits them, and where none exists the site says so.</p>

      <h2 id="refresh">Refresh schedule</h2>
      <table>
        <thead><tr><th>Layer</th><th>Cadence</th></tr></thead>
        <tbody>
          <tr><td>News and media</td><td>Daily</td></tr>
          <tr><td>Parliaments and gazettes</td><td>Weekly</td></tr>
          <tr><td>Trade, finance, investment</td><td>Monthly, or when the source publishes</td></tr>
          <tr><td>Production, reserves, governance indices</td><td>Annual</td></tr>
        </tbody>
      </table>
      <p>&ldquo;Real time&rdquo; means scheduled refreshes, not a live feed. Each panel shows its last update and the sources behind it.</p>

      <h2 id="limitations">Known limitations</h2>
      <p>The full list is maintained in <a href="https://github.com/DomyB/US_vs_China_AI/blob/main/LIMITATIONS.md" className="underline">LIMITATIONS.md</a>. Highlights:</p>
      <ul>
        <li>Phase 0 source verification was search-based because the development sandbox cannot reach most hosts; direct checks run in the first scheduled ingestion.</li>
        <li>No free licensed lithium price benchmark exists; USGS annual averages and customs unit values are used instead.</li>
        <li>Chinese policy-bank lending has no loan-level disclosure; the BU and AidData databases cover sovereign and public borrowers only.</li>
        <li>Bolivia, Guyana, Suriname and Venezuela have no machine-readable legislative records; their Parliament tab states this instead of showing an empty list.</li>
        <li>The Parliament and Media tabs list real bills, votes and headlines (keyword-selected at ingestion, original language); stance, tone, translations and narratives are text-model outputs tagged with their validation status.</li>
        <li>The influence index rests on the ties the warehouse records: US official finance is DFC only (EXIM, CGIT and IDB files pending), Chinese finance ends in 2021 (AidData 3.0), debt by creditor exists for China only, and legislative stance is a zero-shot baseline until the hand-coded sample is adjudicated. Components beyond a source&apos;s coverage are unavailable, not zero.</li>
        <li>SEDAR+ and HKEX forbid scraping; ownership chains for Canadian and Hong Kong intermediaries are built from SEC cross-listings and company reports.</li>
        <li>GDELT is machine-coded and noisy; ACLED covers Latin America only from 2018.</li>
      </ul>
    </div>
  );
}
